[package]
name = "nimble"
version = "0.1.0"
edition = "2021"

[dependencies]
bstr = "1.4.0"
widestring = "1.0.2"
winit = "0.28.3"

[dependencies.windows]
version = "0.46.0"
features = [
    "Win32_Graphics_Direct2D",
    "Win32_Graphics_Direct2D_Common", 
    "Win32_Graphics_DirectWrite",
    "Win32_Graphics_Dxgi",
    "Win32_Graphics_Dxgi_Common",
    "Win32_Foundation", 
    "Foundation_Numerics"
]

[profile.relwithdebinfo]
inherits = "release"
debug = true
